import { AllergenOption } from './types';

export const steps = [
  {
    title: "Personal Details",
    message: "Help us tailor your meal plans to your specific needs. We'll calculate optimal portions and nutrients while considering local, seasonal ingredients to keep your grocery costs down.",
  },
  {
    title: "Food Allergens",
    message: "Your safety is our priority. Let us know about any allergens so we can ensure every recipe is safe for you to enjoy.",
  },
  {
    title: "Food Preferences",
    message: "Tell us what you love (and don't love) to eat. We'll use this information to suggest recipes that match your taste and create enjoyable meal experiences.",
  },
];

export const allergenOptions: AllergenOption[] = [
  {
    id: 'dairy',
    title: 'Dairy',
    icon: '🥛',
    foods: ['Milk', 'Cheese', 'Yogurt', 'Butter', 'Cream'],
  },
  {
    id: 'nuts',
    title: 'Tree Nuts',
    icon: '🥜',
    foods: ['Almonds', 'Walnuts', 'Cashews', 'Pecans', 'Pine Nuts'],
  },
  {
    id: 'shellfish',
    title: 'Shellfish',
    icon: '🦐',
    foods: ['Shrimp', 'Crab', 'Lobster', 'Mussels', 'Clams'],
  },
  {
    id: 'gluten',
    title: 'Gluten',
    icon: '🌾',
    foods: ['Wheat', 'Barley', 'Rye', 'Bread', 'Pasta'],
  },
  {
    id: 'eggs',
    title: 'Eggs',
    icon: '🥚',
    foods: ['Chicken Eggs', 'Duck Eggs', 'Quail Eggs'],
  },
  {
    id: 'soy',
    title: 'Soy',
    icon: '🫘',
    foods: ['Soybeans', 'Tofu', 'Miso', 'Tempeh', 'Edamame'],
  },
];

export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
].sort((a, b) => a.label.localeCompare(b.label));

